### PR TITLE
ReadMe file position fix

### PR DESCRIPTION
**Pull request by PoLaKoSz**
**News Feed** is now in the center of it's own column.

### CODE REVIEW

**Comment by PoLaKoSz** [comment]
Sorry, I'm a beginner but I want to start to learn (code, Version Control and  English too).

**Comment by aalok05** [comment]
Hey! Please make the base of this PR as `dev` branch. Everything else seems fine 👍

**Comment by PoLaKoSz** [comment]
Sorry this is my first PR to a not owned repo, but won't happen again.

**Comment by aalok05** [comment]
@PoLaKoSz  You don't have to apologize :blush:

**Pull request merged**
