### PR TITLE
Add Turkish translation

### PR DESCRIPTION
**Pull request by berkantkz**
## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting)
[ ] Refactoring (no functional changes, no api changes)
[x] Documentation content changes
[x] Other... Please describe: Translation
```

## What is the current behavior?
It doesn't include Turkish translation.

## What is the new behavior?
It does now include Turkish translation.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
No additional information required.

### CODE REVIEW

**Comment by aalok05** [comment]
Looks good

**Comment by aalok05** [comment]
Hey @berkantkz I've changed the base branch to `dev` and there seems to be a conflict. Can you have a look?

**Comment by aalok05** [comment]
It seems you have replaced the English file with the Turkish file, instead of just adding the Turkish file.

**Comment by berkantkz** [comment]
Oh, maybe 😄 I may have forgotten to copy all the stuff and paste in a newly created language file. Sorry for mismatches.

**Comment by aalok05** [comment]
No worries 😄

**Pull request closed without merging**
