### PR TITLE
Develop/UI bugfixes

### PR DESCRIPTION
**Pull request by PoLaKoSz**

### CODE REVIEW

**Comment by PoLaKoSz** [comment]
Maybe better if you rename the
**Fixed #49 - ("Star on GItHub" jump to the project repo)**
to
**Fixed #49 - ("Star on GItHub" jump to the application repo)**

**Comment by aalok05** [comment]
@PoLaKoSz I don't think renaming the commit is necessary. Anyway nice work man! We need to add your name to Contributor's list in About page 😄

**Comment by PoLaKoSz** [comment]
Hope I will be useful :)

**Comment by aalok05** [comment]
c61694552174438d410183eb3e8586788457a439 Here you go.

**Comment by PoLaKoSz** [comment]
Thank you so much.

**Pull request merged**
