### PR TITLE
Initial Hungarian translate

### PR DESCRIPTION
**Pull request by PoLaKoSz**
This version is not finished yet, need to maintain this code.

### CODE REVIEW

**Comment by PoLaKoSz** [comment]
I will continue the translation after this (#44) issue solved.

**Comment by aalok05** [comment]
Nice work @PoLaKoSz 👍 Do you want me to merge this or are you going to make more changes?

**Comment by PoLaKoSz** [comment]
Yeah, pleas leave it open a few more days. Thanks

**Comment by PoLaKoSz** [comment]
You can merge now @aalok05 , thanks.

**Comment by aalok05** [comment]
Cool. I'll merge this

**Pull request merged**
