### PR TITLE
Watch button show the correct number

### LINKED ISSUE #55: Repository Watch count bug
- [X] Not display the number of the people who watch the current repository
- [ ] After hitting the 'Watch' button UI not refresh the new count

I will try tomorrow fix these problems.

### PR DESCRIPTION
**Pull request by PoLaKoSz**
Fixed #55

### CODE REVIEW

**Comment by PoLaKoSz** [comment]
Please not merge yet if looks good for you, because I want to dive deeper why something broken in Octokit [Octocit/#1470](https://github.com/octokit/octokit.net/issues/1470).

**Comment by PoLaKoSz** [comment]
This small code sample works fine, so something wrong in our application:
```cs
using System;
using Octokit;

namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            Start();
            
            Console.Read();
        }

        private async static void Start()
        {
            var client = new GitHubClient(new ProductHeaderValue("OctoKitTestApp"));

            var repository = await client.Repository.Get("aalok05", "CodeHub");
        }
    }
}
```

**Comment by PoLaKoSz** [comment]
Created an issue on [OctoKit](https://github.com/octokit/octokit.net/issues/1624) hope I get an answer. :)

**Comment by PoLaKoSz** [comment]
It's really sad, I think the original GitHub API is the reason why the UI shows the wrong number [(OctoKit.NET)](https://github.com/octokit/octokit.net/issues/1624#issuecomment-313931046)
If you reviewed my code and fine I won't add more code to it so you can merge it.

**Comment by aalok05** [comment]
Made some changes here 7d58c96e9ce7ee727880c827751c96892a0c647f . We'll use the new method only if existing SubscribersCount property returns 0. This way we have to call the API method fewer times.

**Comment by PoLaKoSz** [comment]
Thanks for the feedback.

**Pull request merged**
