### PR TITLE
fix-portuguese_translation

### PR DESCRIPTION
**Pull request by JNMarcos**
## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[x ] Other... Please describe: Translation
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x ] No
```

### CODE REVIEW

**Comment by aalok05** [comment]
Thanks @JNMarcos !

**Comment by aalok05** [comment]
Hey @JNMarcos , there is an issue where some characters are being replaced with unicode question mark (�) character. Can you make sure that these characters appear as expected in the app?

**Comment by JNMarcos** [comment]
I had forgotten to save as UTF-8. Fixed.

**Comment by aalok05** [comment]
Great. Merging this.

**Pull request merged**
