### PR TITLE
Multilanguage support

### PR DESCRIPTION
**Pull request by PoLaKoSz**
Hy :)

Please don't merge it yet if it looks good for you I will add more commits.

### CODE REVIEW

**Comment by PoLaKoSz** [comment]
This is only translated to hungarian so need some help.  #73

**Comment by aalok05** [comment]
@Darkpingouin  can you help with #75 ?

**Comment by Darkpingouin** [comment]
@aalok05 yes I will work on it today

**Comment by PoLaKoSz** [comment]
@aalok05 Can You merge it if it looks good for You?

**Comment by PoLaKoSz** [comment]
I am done.

**Comment by aalok05** [comment]
Great! I think we'll leave Vietnamese, Chinese and Spanish open for now. But I'll merge the PR

**Comment by PoLaKoSz** [comment]
Okey

**Pull request merged**
